language: c

branches:
  only:
    - cppcheck

sudo: false

cache:
  directories:
    - $HOME/travis-cache

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    packages:
    - cppcheck

script:
  - make cppcheck
  - make cppcheck CPPCHECK_SUPP=

notifications:
  email: false
